CUDA_VISIBLE_DEVICE=1 density=0.975 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.95 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.925 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.9 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.875 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.85 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.825 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.8 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.775 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.75 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.725 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.7 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.675 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.65 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.625 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.6 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.575 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.55 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.525 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.5 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.475 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.45 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.425 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.4 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.375 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.35 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.325 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.3 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.275 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.25 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.225 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.2 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.175 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.15 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.125 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
CUDA_VISIBLE_DEVICE=1 density=0.1 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml


#CUDA_VISIBLE_DEVICE=1 density=0.9836 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.9584 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.9331 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.9079 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.8827 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.8575 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.8323 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.8070 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.7818 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.7566 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.7314 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.7062 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.6809 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.6557 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.6305 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.6053 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.5801 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.5548 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.5296 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.5044 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.4792 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.4540 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.4287 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.4035 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.3783 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.3531 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.3279 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.3026 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.2774 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.2522 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.2270 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.2018 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.1765 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.1513 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.1261 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
#CUDA_VISIBLE_DEVICE=1 density=0.1009 scale=0.01 python3 xnnpack_experiment.py app:app/mbv2-global.yml
