#model Arch config
model: models.gp_mobilenet_v2
width_mult: 0.35
density_list : [1.0, 0.3, 0.2, 0.1]
density_mult: 1.0
DL: 0.1
DH: 1.0
BS_R: 1
BS_C: 2

#seed
random_seed: 0

# data info - dataset
dataset: CIFAR100
data_transforms: cifar
data_loader: cifar
dataset_dir: /home/hayun/data
image_size: 32
num_classes: 100

# data norm - recepi
normalize: True
mean: [0.0, 0.0, 0.0]
std: [1.0, 1.0, 1.0]

#data info - dataloader (batch size / )
batch_size: 256
drop_last: True
data_loader_workers: 4

#optimizer
optimizer: sgd
lr: 0.1
lr_scheduler: cosine_decaying
lr_warmup: False
momentum: 0.9
nesterov: True
weight_decay: 4.0e-5
lr_warmup_epochs: 5
num_epochs: 3

# phase
calibrate_bn: True
test_only: False

# Wrapper
dataparallel: False
distributed: False

# model pre-trained
pretrained: False
pretrained_model_remap_keys: False

#profiling
profiling: False
profiling_only: False
profiling_verbose: False

# training spec
pruner: local

# Training
IPKD: True
num_samples_training: 4
pruner: local
DST_TRAIN: True
DENSE_TEACHER: True

# no batch norm calibration
track_running_stats: True
cumulative_bn_stats: True
bn_cal_batch_num: 10

